package Nimbus_Rating_DB;
// Generated 10-Aug-2011 12:39:33 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AggregatedCdr generated by hbm2java
 */
public class AggregatedCdr  implements java.io.Serializable {


     private int id;
     private String userId;
     private String date;
     private String aggregationId;
     private double retailPrice;
     private double wholesalePrice;
     private double remotePolo;
     private double remoteRolo;
     private double localPolo;
     private double localRolo;
     private double localTransit;
     private double remoteTransit;
     private Double deltaBal;
     private String status;
     private String billId;
     private String financialCode;
     private Date modTimestamp;
     private String network;
     private Double currentBal;
     private String user;
     private String aliasStatus;

    public AggregatedCdr() {
    }

	
    public AggregatedCdr(int id, String userId, String date, String aggregationId, double retailPrice, double wholesalePrice, double remotePolo, double remoteRolo, double localPolo, double localRolo, double localTransit, double remoteTransit, String status, String billId, String financialCode) {
        this.id = id;
        this.userId = userId;
        this.date = date;
        this.aggregationId = aggregationId;
        this.retailPrice = retailPrice;
        this.wholesalePrice = wholesalePrice;
        this.remotePolo = remotePolo;
        this.remoteRolo = remoteRolo;
        this.localPolo = localPolo;
        this.localRolo = localRolo;
        this.localTransit = localTransit;
        this.remoteTransit = remoteTransit;
        this.status = status;
        this.billId = billId;
        this.financialCode = financialCode;
    }
    public AggregatedCdr(int id, String userId, String date, String aggregationId, double retailPrice, double wholesalePrice, double remotePolo, double remoteRolo, double localPolo, double localRolo, double localTransit, double remoteTransit, Double deltaBal, String status, String billId, String financialCode, Date modTimestamp, String network, Double currentBal, String user, String aliasStatus) {
       this.id = id;
       this.userId = userId;
       this.date = date;
       this.aggregationId = aggregationId;
       this.retailPrice = retailPrice;
       this.wholesalePrice = wholesalePrice;
       this.remotePolo = remotePolo;
       this.remoteRolo = remoteRolo;
       this.localPolo = localPolo;
       this.localRolo = localRolo;
       this.localTransit = localTransit;
       this.remoteTransit = remoteTransit;
       this.deltaBal = deltaBal;
       this.status = status;
       this.billId = billId;
       this.financialCode = financialCode;
       this.modTimestamp = modTimestamp;
       this.network = network;
       this.currentBal = currentBal;
       this.user = user;
       this.aliasStatus = aliasStatus;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getAggregationId() {
        return this.aggregationId;
    }
    
    public void setAggregationId(String aggregationId) {
        this.aggregationId = aggregationId;
    }
    public double getRetailPrice() {
        return this.retailPrice;
    }
    
    public void setRetailPrice(double retailPrice) {
        this.retailPrice = retailPrice;
    }
    public double getWholesalePrice() {
        return this.wholesalePrice;
    }
    
    public void setWholesalePrice(double wholesalePrice) {
        this.wholesalePrice = wholesalePrice;
    }
    public double getRemotePolo() {
        return this.remotePolo;
    }
    
    public void setRemotePolo(double remotePolo) {
        this.remotePolo = remotePolo;
    }
    public double getRemoteRolo() {
        return this.remoteRolo;
    }
    
    public void setRemoteRolo(double remoteRolo) {
        this.remoteRolo = remoteRolo;
    }
    public double getLocalPolo() {
        return this.localPolo;
    }
    
    public void setLocalPolo(double localPolo) {
        this.localPolo = localPolo;
    }
    public double getLocalRolo() {
        return this.localRolo;
    }
    
    public void setLocalRolo(double localRolo) {
        this.localRolo = localRolo;
    }
    public double getLocalTransit() {
        return this.localTransit;
    }
    
    public void setLocalTransit(double localTransit) {
        this.localTransit = localTransit;
    }
    public double getRemoteTransit() {
        return this.remoteTransit;
    }
    
    public void setRemoteTransit(double remoteTransit) {
        this.remoteTransit = remoteTransit;
    }
    public Double getDeltaBal() {
        return this.deltaBal;
    }
    
    public void setDeltaBal(Double deltaBal) {
        this.deltaBal = deltaBal;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBillId() {
        return this.billId;
    }
    
    public void setBillId(String billId) {
        this.billId = billId;
    }
    public String getFinancialCode() {
        return this.financialCode;
    }
    
    public void setFinancialCode(String financialCode) {
        this.financialCode = financialCode;
    }
    public Date getModTimestamp() {
        return this.modTimestamp;
    }
    
    public void setModTimestamp(Date modTimestamp) {
        this.modTimestamp = modTimestamp;
    }
    public String getNetwork() {
        return this.network;
    }
    
    public void setNetwork(String network) {
        this.network = network;
    }
    public Double getCurrentBal() {
        return this.currentBal;
    }
    
    public void setCurrentBal(Double currentBal) {
        this.currentBal = currentBal;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getAliasStatus() {
        return this.aliasStatus;
    }
    
    public void setAliasStatus(String aliasStatus) {
        this.aliasStatus = aliasStatus;
    }




}


