package Nimbus_Rating_DB;
// Generated 21-Sep-2011 10:52:12 by Hibernate Tools 3.2.1.GA



/**
 * DestinationMap generated by hbm2java
 */
public class DestinationMap  implements java.io.Serializable {


     private int id;
     private String mapGroup;
     private String prefix;
     private String tierCode;
     private String description;
     private String category;

    public DestinationMap() {
    }

	
    public DestinationMap(int id) {
        this.id = id;
    }
    public DestinationMap(int id, String mapGroup, String prefix, String tierCode, String description, String category) {
       this.id = id;
       this.mapGroup = mapGroup;
       this.prefix = prefix;
       this.tierCode = tierCode;
       this.description = description;
       this.category = category;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMapGroup() {
        return this.mapGroup;
    }
    
    public void setMapGroup(String mapGroup) {
        this.mapGroup = mapGroup;
    }
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }
    public String getTierCode() {
        return this.tierCode;
    }
    
    public void setTierCode(String tierCode) {
        this.tierCode = tierCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }




}


