package Nimbus_Rating_DB;
// Generated 17-Oct-2011 13:36:04 by Hibernate Tools 3.2.1.GA



/**
 * Geo generated by hbm2java
 */
public class Geo  implements java.io.Serializable {


     private GeoId id;

    public Geo() {
    }

    public Geo(GeoId id) {
       this.id = id;
    }
   
    public GeoId getId() {
        return this.id;
    }
    
    public void setId(GeoId id) {
        this.id = id;
    }




}


