package Nimbus_Rating_DB;
// Generated 17-Oct-2011 13:30:45 by Hibernate Tools 3.2.1.GA



/**
 * NonGeo generated by hbm2java
 */
public class NonGeo  implements java.io.Serializable {


     private NonGeoId id;

    public NonGeo() {
    }

    public NonGeo(NonGeoId id) {
       this.id = id;
    }
   
    public NonGeoId getId() {
        return this.id;
    }
    
    public void setId(NonGeoId id) {
        this.id = id;
    }




}


